### ISSUE TITLE
Examples can't be viewed

### ISSUE THREAD

**Issue by chfight** [Autodesk-Forge/library-javascript-viewer-extensions#3]
I want to see these examples, but I can't open the website. How can I view it?

**Comment by leefsmp** [comment]
Sorry the web site was ageing and we took it down. I don't have a full replacement at the moment but you can take a look there, those are more advanced examples with source code as well:
[https://forge-rcdb.autodesk.io/configurator](https://forge-rcdb.autodesk.io/configurator)
